/* ═══════════════════════════════════════════════════════════════
   HOMEPAGE - lazy below-fold choreography and widgets
   Generated by splitting js/app.js so the canvas hero stays critical
   while lower-page interactions load near use.
   ═══════════════════════════════════════════════════════════════ */

window.DE.initHomeLate = function initHomeLate(context) {
  'use strict';
  const { lenis, runWhenNear, loadHomeLateCss } = context || {};
  if (window.DE.__homeLateInitialized) return;
  window.DE.__homeLateInitialized = true;

// ─── RIPPLE EFFECT ───
function initRippleEffect() {
  const canvas = document.getElementById('ripple-canvas');
  if (!canvas) return;
  const ctx = canvas.getContext('2d');
  if (!ctx) return;
  const section = canvas.parentElement;
  if (!section) return;

  const SCALE = 0.5, DAMPING = 0.985, STRENGTH = 220, BRUSH = 6;
  let w = 0, h = 0, buf1, buf2, srcData, outImg;
  let mouseX = 0, mouseY = 0, hovering = false, lastAuto = 0;
  let rippleImg = null;

  function setup(img) {
    const cssW = canvas.parentElement ? canvas.parentElement.offsetWidth : 0;
    if (!cssW || !img.naturalWidth) return false;
    const cssH = Math.round(cssW * img.naturalHeight / img.naturalWidth);
    w = Math.round(cssW * SCALE);
    h = Math.round(cssH * SCALE);
    canvas.width = w;
    canvas.height = h;
    canvas.style.height = cssH + 'px';
    buf1 = new Float32Array(w * h);
    buf2 = new Float32Array(w * h);
    outImg = ctx.createImageData(w, h);
    // Draw image to an offscreen canvas we own, then read pixels.
    // getImageData on an owned canvas is permitted on localhost (same-origin).
    const off = document.createElement('canvas');
    off.width = w; off.height = h;
    const offCtx = off.getContext('2d');
    offCtx.drawImage(img, 0, 0, w, h);
    try {
      srcData = offCtx.getImageData(0, 0, w, h).data;
    } catch (e) {
      return false; // file:// strict security — graceful fallback to CSS bg
    }
    return true;
  }

  function disturb(ix, iy) {
    ix = Math.round(ix); iy = Math.round(iy);
    for (let dy = -BRUSH; dy <= BRUSH; dy++) {
      for (let dx = -BRUSH; dx <= BRUSH; dx++) {
        const nx = ix + dx, ny = iy + dy;
        if (nx > 0 && nx < w - 1 && ny > 0 && ny < h - 1) buf1[ny * w + nx] = STRENGTH;
      }
    }
  }

  function tick(ts) {
    if (!w || !srcData) return;

    // Auto-disturb every 2s so ripples are visible without hovering
    if (ts - lastAuto > 2000) {
      disturb(
        w * 0.25 + Math.random() * w * 0.5,
        h * 0.25 + Math.random() * h * 0.5
      );
      lastAuto = ts;
    }

    // Wave physics
    for (let y = 1; y < h - 1; y++) {
      for (let x = 1; x < w - 1; x++) {
        const i = y * w + x;
        buf2[i] = (buf1[i - 1] + buf1[i + 1] + buf1[i - w] + buf1[i + w]) * 0.5 - buf2[i];
        buf2[i] *= DAMPING;
      }
    }
    const tmp = buf1; buf1 = buf2; buf2 = tmp;

    // Render: displace each pixel by the local wave gradient
    const dst = outImg.data;
    for (let y = 0; y < h; y++) {
      for (let x = 0; x < w; x++) {
        const i = y * w + x;
        let sx = x, sy = y;
        if (x > 0 && x < w - 1 && y > 0 && y < h - 1) {
          sx = Math.max(0, Math.min(w - 1, Math.round(x + (buf1[i - 1] - buf1[i + 1]) * 0.025)));
          sy = Math.max(0, Math.min(h - 1, Math.round(y + (buf1[i - w] - buf1[i + w]) * 0.025)));
        }
        const si = (sy * w + sx) << 2;
        const di = i << 2;
        dst[di]     = srcData[si];
        dst[di + 1] = srcData[si + 1];
        dst[di + 2] = srcData[si + 2];
        dst[di + 3] = 255;
      }
    }
    ctx.putImageData(outImg, 0, 0);
  }

  section.addEventListener('mousemove', e => {
    const r = canvas.getBoundingClientRect();
    if (r.width > 0) {
      mouseX = (e.clientX - r.left) * (w / r.width);
      mouseY = (e.clientY - r.top)  * (h / r.height);
    }
    if (hovering) disturb(mouseX, mouseY);
  }, { passive: true });
  section.addEventListener('mouseenter', () => { hovering = true; });
  section.addEventListener('mouseleave', () => { hovering = false; });
  DE.on(window, 'resize', () => {
    if (rippleImg && rippleImg.complete && rippleImg.naturalWidth) setup(rippleImg);
  }, { passive: true });

  const img = new Image();
  rippleImg = img;
  img.onload = () => {
    section.style.backgroundImage = "url('assets/dealer-edge-case-studies-background.webp')";
    setTimeout(() => { if (setup(img)) DE.rafLoop(tick); }, 100);
  };
  img.src = 'assets/dealer-edge-case-studies-background.webp';
}

// ─── VIDEO SECTION ───
function animateVideoSection() {
  const inner   = document.getElementById('video-inner');
  const overlay = document.getElementById('video-overlay-text');
  const section = document.getElementById('video-section');
  if (!inner || !section) return;

  const picture = inner.querySelector('[data-video-thumb]');
  if (picture && !picture.dataset.loaded) {
    picture.querySelectorAll('source[data-srcset]').forEach((source) => {
      source.srcset = source.dataset.srcset;
    });
    const img = picture.querySelector('img[data-src]');
    if (img) img.src = img.dataset.src;
    picture.dataset.loaded = 'true';
  }

  // Expand from 800px to full viewport width on scroll
  gsap.to(inner, {
    width: '100%',
    maxWidth: '100%',
    borderRadius: 0,
    ease: 'none',
    scrollTrigger: {
      trigger: section,
      start: 'top 65%',
      end: 'center center',
      scrub: 1,
    },
  });

  // Text fades in once image is centred in the viewport
  ScrollTrigger.create({
    trigger: inner,
    start: 'center center',
    onEnter:     () => overlay.classList.add('visible'),
    onLeaveBack: () => overlay.classList.remove('visible'),
  });
}

// ─── JOURNEY TIMELINE ───
function animateJourney() {
  const lineFill = document.querySelector('.journey-line-fill');
  const timeline = document.querySelector('.journey-timeline');
  if (!lineFill || !timeline) return;

  // Line grows downward as user scrolls through the section
  gsap.to(lineFill, {
    height: '100%',
    ease: 'none',
    scrollTrigger: {
      trigger: timeline,
      start: 'top 70%',
      end: 'bottom 65%',
      scrub: 0.8,
    },
  });

  // Each point: card slides in + dot activates
  document.querySelectorAll('.journey-point').forEach((point) => {
    const card = point.querySelector('.journey-card');
    const isLeft = point.classList.contains('journey-point--left');

    gsap.fromTo(
      card,
      { opacity: 0, x: isLeft ? -36 : 36 },
      {
        opacity: 1,
        x: 0,
        duration: 0.85,
        ease: 'power2.out',
        scrollTrigger: {
          trigger: point,
          start: 'top 72%',
          toggleActions: 'play none none none',
          onEnter: () => point.classList.add('active'),
        },
      }
    );
  });
}

// ─── CUSTOM CURSOR + JOURNEY MODAL ───
function initCustomCursor() {
  const cursor   = document.getElementById('custom-cursor');
  const cards = document.querySelectorAll('.journey-card[data-journey]');
  if (!cursor) return;
  let journeyModalPromise = null;

  function loadJourneyModal() {
    const existing = document.getElementById('journey-modal-backdrop');
    if (existing) return Promise.resolve(existing);
    if (!journeyModalPromise) {
      journeyModalPromise = Promise.all([
        loadHomeLateCss ? loadHomeLateCss() : Promise.resolve(),
        fetch('partials/journey-modal.html?v=20260630a')
          .then((response) => response.ok ? response.text() : '')
      ]).then(([, html]) => {
        if (!html) return null;
        const template = document.createElement('template');
        template.innerHTML = html.trim();
        const modal = template.content.firstElementChild;
        if (!modal) return null;
        document.body.appendChild(modal);
        return modal;
      });
    }
    return journeyModalPromise;
  }

  // Position updates instantly on every mousemove, no lerp, pixel-perfect
  DE.on(window, 'mousemove', (e) => {
    cursor.style.left = e.clientX + 'px';
    cursor.style.top  = e.clientY + 'px';
  }, { passive: true });

  // Video section hover, dot grows into play circle
  const videoInner = document.getElementById('video-inner');
  if (videoInner) {
    videoInner.addEventListener('mouseenter', () => cursor.classList.add('video-active'));
    videoInner.addEventListener('mouseleave', () => cursor.classList.remove('video-active'));
  }

  // Case study card hover, same "Learn More" cursor
  document.querySelectorAll('.cs-card').forEach((card) => {
    card.addEventListener('mouseenter', () => cursor.classList.add('journey-active'));
    card.addEventListener('mouseleave', () => cursor.classList.remove('journey-active'));
  });

  // Journey card hover, dot grows into glass circle in place
  cards.forEach((card) => {
    card.addEventListener('mouseenter', () => {
      cursor.classList.add('journey-active');
      loadJourneyModal();
    });
    card.addEventListener('mouseleave', () => cursor.classList.remove('journey-active'));
    card.addEventListener('focus', loadJourneyModal);

    card.addEventListener('click', () => {
      const title = card.getAttribute('data-journey');
      loadJourneyModal().then((backdrop) => {
        if (!backdrop) return;
        showPanel(title);
        backdrop.classList.add('is-open');
        backdrop.setAttribute('aria-hidden', 'false');
        document.body.style.overflow = 'hidden';
        lenis.stop();
        cursor.classList.remove('journey-active');
      });
    });
  });

  // Nav arrows, switch between panels
  function showPanel(title) {
    document.querySelectorAll('[data-journey-content]').forEach((panel) => {
      panel.style.display = panel.getAttribute('data-journey-content') === title ? '' : 'none';
    });
  }

  DE.on(document, 'click', (e) => {
    const btn = e.target.closest('.jm-nav-btn');
    if (!btn) return;
    const target = btn.getAttribute('data-nav-to');
    if (target) showPanel(target);
  });

  function closeJourneyModal() {
    const backdrop = document.getElementById('journey-modal-backdrop');
    if (!backdrop) return;
    backdrop.classList.remove('is-open');
    backdrop.setAttribute('aria-hidden', 'true');
    document.body.style.overflow = '';
    lenis.start();
  }

  DE.on(document, 'click', (e) => {
    if (e.target.closest('.jm-close')) closeJourneyModal();
  });
  DE.on(document, 'click', (e) => {
    if (e.target?.id === 'journey-modal-backdrop') closeJourneyModal();
  });
  DE.on(document, 'keydown', (e) => {
    const backdrop = document.getElementById('journey-modal-backdrop');
    if (e.key === 'Escape' && backdrop?.classList.contains('is-open')) closeJourneyModal();
  });
}

// ─── BOAT SECTION ───
function initBoatSection() {
  const section = document.getElementById('boat-section');
  const video   = document.getElementById('boat-video');
  const headOut = document.querySelector('.boat-headline--out');
  const headIn  = document.querySelector('.boat-headline--in');
  const boatSub = document.getElementById('boat-sub');
  const boatCta = document.getElementById('boat-cta');
  if (!section || !video) return;
  let videoRequested = false;

  function requestVideo() {
    if (videoRequested) return;
    const src = video.getAttribute('data-src');
    if (!src) return;
    videoRequested = true;
    video.preload = 'auto';
    video.src = src;
    video.load();
    video.pause();
  }

  // Keep video paused, scroll drives currentTime
  video.pause();
  runWhenNear('#boat-section', requestVideo, '1800px 0px');

  function scrub(progress) {
    requestVideo();
    if (video.readyState >= 1 && video.duration) {
      video.currentTime = progress * video.duration;
    }
  }

  // Scroll drives video playback
  ScrollTrigger.create({
    trigger: section,
    start: 'top top',
    end:   'bottom bottom',
    onUpdate: (self) => scrub(self.progress),
  });

  // Text swap: out at 20%, second headline in at 28%, sub at 33%, button at 37%
  gsap.timeline({
    scrollTrigger: {
      trigger: section,
      start: 'top top',
      end:   'bottom bottom',
      scrub: 1,
    }
  })
  .to(headOut,     { opacity: 0, y: -30, duration: 0.1,  ease: 'power2.in'  }, 0.20)
  .fromTo(headIn,  { opacity: 0, y:  30 }, { opacity: 1, y: 0, duration: 0.12, ease: 'power2.out' }, 0.28)
  .fromTo(boatSub, { opacity: 0, y:  16, pointerEvents: 'none' }, { opacity: 1, y: 0, pointerEvents: 'auto', duration: 0.1, ease: 'power2.out' }, 0.33)
  .fromTo(boatCta, { opacity: 0, y:  20, pointerEvents: 'none' }, { opacity: 1, y: 0, pointerEvents: 'auto', duration: 0.1, ease: 'power2.out' }, 0.37);
}

// ─── CASE STUDIES ───
function initCaseStudyCarousel() {
  // Homepage case-study selector retired (2026-06-23): the fabricated demo
  // dealers were replaced with the real Premier Watersports flagship result,
  // hardcoded statically in index.html, plus the OEM pedigree named in copy.
  // No .cs-logo-btn buttons remain, so this no-ops below — kept as a guarded
  // stub so the DE.boot lifecycle call stays valid.
  const CASES = [];

  const detail      = document.getElementById('cs-detail');
  const detailLogo  = document.getElementById('cs-detail-logo');
  const detailStats = document.getElementById('cs-detail-stats');
  const detailQuote = document.getElementById('cs-detail-quote');
  const detailAttr  = document.getElementById('cs-detail-attribution');
  const btns        = Array.from(document.querySelectorAll('.cs-logo-btn'));
  if (!detail || !btns.length) return;

  document.querySelectorAll('img[data-cs-logo-src]').forEach((img) => {
    img.src = img.dataset.csLogoSrc;
  });

  function render(idx) {
    const c = CASES[idx];
    detailLogo.src = c.logo;
    detailStats.innerHTML = c.stats.map(s => `
      <div class="cs-detail-stat">
        <span class="cs-detail-stat-value">${s.value}</span>
        <span class="cs-detail-stat-label">${s.label}</span>
      </div>`).join('');
    detailQuote.textContent = `"${c.quote}"`;
    detailAttr.textContent  = `${c.name}`;
  }

  function select(idx) {
    btns.forEach((b, i) => b.classList.toggle('cs-logo-btn--active', i === idx));
    detail.classList.add('is-switching');
    setTimeout(() => {
      render(idx);
      detail.classList.remove('is-switching');
    }, 200);
  }

  btns.forEach((btn, i) => btn.addEventListener('click', () => select(i)));

  // Initialise with first item
  render(0);
}

// ─── CHATBOT ───
function initChatbot() {
  const widget   = document.getElementById('chatbot-widget');
  const trigger  = document.getElementById('chatbot-trigger');
  const closeBtn = document.getElementById('chatbot-close');
  const messages = document.getElementById('chatbot-messages');
  const input    = document.getElementById('chatbot-input');
  const sendBtn  = document.getElementById('chatbot-send');
  if (!widget || !trigger) return;

  // ── Responses ──
  const responses = [
    { match: /hello|hi|hey|howdy/i,
      reply: "Hey! Great to have you here. What can I help you with today, features, pricing, or getting started?" },
    { match: /price|pricing|cost|how much|plans/i,
      reply: "Pricing is tailored to your dealership's size and needs. The best way to get a number is a quick call with our team, want me to point you to the contact form?" },
    { match: /feature|what can|what does|offer|include/i,
      reply: "DealerEdge covers the full customer journey: AI marketing, smart listings, instant lead response, and sales analytics, all in one platform. Which area interests you most?" },
    { match: /market|ad|advertis|social|seo/i,
      reply: "Our AI generates high-converting ads, SEO content, and social posts tailored to your live inventory, automatically, no agency needed." },
    { match: /listing|inventory|vehicle|car|boat|rv/i,
      reply: "DealerEdge publishes polished listings across every major platform in seconds. AI writes the descriptions, optimises photos, and manages pricing for you." },
    { match: /lead|response|inquiry|follow.?up/i,
      reply: "Our AI responds to leads in seconds, qualifies buyers, and books appointments 24/7, even while your team sleeps." },
    { match: /analytic|track|dashboard|report|data/i,
      reply: "Real-time dashboards show every deal from first touch to close, broken down by channel, salesperson, and vehicle type." },
    { match: /loyalt|repeat|retention|customer/i,
      reply: "DealerEdge keeps customers engaged after the sale through automated follow-ups, service reminders, and personalised outreach, turning buyers into advocates." },
    { match: /start|demo|trial|sign.?up|onboard/i,
      reply: "Getting started is simple! Fill out the contact form on this page and our team will reach out within one business day. Want me to scroll you there?" },
    { match: /contact|email|phone|call|reach|talk/i,
      reply: "You can reach us at contact@dealeredge.com or use the Get Started form on this page. Our team typically responds within a few hours." },
    { match: /thank|thanks|great|awesome|perfect/i,
      reply: "Happy to help! Anything else you'd like to know about DealerEdge?" },
    { match: /bye|goodbye|see you/i,
      reply: "Talk soon! Feel free to come back any time. 👋" },
  ];

  function getReply(text) {
    for (const { match, reply } of responses) {
      if (match.test(text)) return reply;
    }
    return "That's a great question! For the most detailed answer I'd recommend chatting with our team directly. Want me to point you to the contact form?";
  }

  // ── DOM helpers ──
  function addMessage(text, type) {
    const div = document.createElement('div');
    div.className = `chat-msg chat-msg--${type}`;
    const p = document.createElement('p');
    p.textContent = text;
    div.appendChild(p);
    messages.appendChild(div);
    messages.scrollTop = messages.scrollHeight;
    return div;
  }

  function showTyping() {
    const div = document.createElement('div');
    div.className = 'chat-msg chat-msg--bot chat-msg--typing';
    div.innerHTML = '<p><span class="typing-dot"></span><span class="typing-dot"></span><span class="typing-dot"></span></p>';
    messages.appendChild(div);
    messages.scrollTop = messages.scrollHeight;
    return div;
  }

  function send() {
    const text = input.value.trim();
    if (!text) return;
    input.value = '';

    addMessage(text, 'user');
    const typing = showTyping();

    setTimeout(() => {
      typing.remove();
      addMessage(getReply(text), 'bot');
    }, 900 + Math.random() * 500);
  }

  // ── Open / close ──
  let hasOpened = false;

  function open() {
    widget.classList.add('is-open');
    input.focus();
    if (!hasOpened) {
      hasOpened = true;
      setTimeout(() => {
        const div = addMessage('Want to see how your dealership can respond to every lead instantly and close more deals?', 'bot');
        div.classList.add('chat-msg--animate-in');
      }, 800);
    }
  }

  function close() { widget.classList.remove('is-open'); }

  trigger.addEventListener('click', () => widget.classList.contains('is-open') ? close() : open());
  closeBtn.addEventListener('click', close);
  sendBtn.addEventListener('click', send);
  input.addEventListener('keydown', (e) => { if (e.key === 'Enter') send(); });
}



  runWhenNear('.case-studies-section', initRippleEffect, '0px 0px');
  runWhenNear('#video-section', () => {
    loadHomeLateCss().then(() => {
      animateVideoSection();
      initBoatSection();
      if (window.ScrollTrigger) ScrollTrigger.refresh();
    });
  }, '0px 0px');
  animateJourney();
  initCustomCursor();
  runWhenNear('.case-studies-section', initCaseStudyCarousel, '0px 0px');
  initChatbot();
};
